# Set?rile de conexiune la MySQL (asigur?-te c? ai creat o baz? de date goal? numit? 'audit_db' în MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/audit_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234

# Aceasta este "magia" Code-First. 'update' îi spune lui Hibernate s? creeze sau s? actualizeze tabelele automat pe baza claselor Java.
spring.jpa.hibernate.ddl-auto=update

# Op?ional: afi?eaz? în consol? comenzile SQL generate în fundal (util pentru debugging)
spring.jpa.show-sql=true